{% block jumbotron %}
    <!--img src="/assets/images/slideshow/default.jpg" class="homeSlide_imgs" title=""-->
    <!--video autoplay>
        <source  type="video/mp4" src="/assets/media/video/default_video.mp4">
    </video-->
    <div id="s5" class="homeSlide">
        <img class="homeSlide_imgs" alt="{{ siteName }}"
             src="assets/images/slideshow/Free-Hip-Hop-Wallpaper.jpg" />
        <!--img class="homeSlide_imgs" alt="{{ siteName }}"
             src="assets/images/slideshow/default_image1.jpg" />
        <img class="homeSlide_imgs" alt="{{ siteName }}"
             src="assets/images/slideshow/default_image2.jpg" /-->
    </div>
{% endblock %}