<footer>
    <!-- START FOOTER NAV WRAPPER -->
    <div class="footer-nav">
        <ul>
            <li><a href="/">{{ siteName }} &copy; {{ siteYear }}</a></li>
            <li><a href="/about/index">BIO</a></li>
            <li><a href="/music/index">MUSIC</a></li>
            <li><a href="/video/index">VIDEO</a></li>
            <li><a href="/contact/index">CONTACT</a></li>
        </ul>
    </div>
    <div class="site-footer">
        {{ siteName }} &copy; {{ siteYear }}
        <a href="/">
        </a> is powered by getMarvelle CMS.  getMarvelle CMS is a copyrighted and a registered trademark. The JUKEBOX theme was develop by webmaster
        <a href="http://www.marvintdawson.com">Marvin Dawson</a>. Hosted by Home Grown Musiq Network LLC.
    </div>
</footer>