<div class="mast-head">
    <div class="col-md-8 logo-wrapper">
        <a href="/">
            <img class="logo" src="../../assets/images/logo.png" alt="HGM Logo">
        </a>
    </div>
        <div class="nav-mobile-button"></div>
        <!-- START Navigation Links -->
        <div class="col-md-4 nav-link-wrapper">
            <ul>
                <li class="nav-link"><a href="/about/index">BIO</a></li>
                <li class="nav-link"><a href="/music/index">MUSIC</a></li>
                <li class="nav-link"><a href="/video/index">VIDEO</a></li>
                <li class="nav-link"><a href="/contact/index">CONTACT</a></li>
            </ul>
        </div>
</div><!-- #end mast head -->